<!-- Bootstrap -->
<link rel="stylesheet" href="<?=DIR_BS?>css/bootstrap.min.css">
<!-- <link rel="stylesheet" href="https://bootswatch.com/flatly/bootstrap.min.css"> -->
<!-- ESTILOS -->
<link rel="stylesheet" href="<?=DIR_RS?>css/main.css">
<link rel="stylesheet" href="<?=DIR_RS?>css/affix.css">
<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
	<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
	<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
<!-- JS Archives -->
<!--  jQuery All version https://developers.google.com/speed/libraries/#jquery -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.3/jquery.min.js"></script>
<script src="<?=DIR_RS?>js/jquery.js"></script>
<script src="<?=DIR_RS?>js/scroll.js" type="text/javascript"></script>
<!-- <script src="<?=DIR_BS?>js/bootstrap.min.js"></script>	 -->
<!-- JS Archives APP -->
<script src="core/js/generales.js" type="text/javascript"></script>