<section id="foot">
  <div class="container">
    <div class="row row-foot">
	    <div class="col-lg-12 header-foot">
	    	<h5>Site Map</h5>       
	    </div>
	    <div class="col-lg-12 foot-foot">
	      	<div class="nav-foot">
	      		<div class="cont-data-foot">
	      			<p class="separador-nav-foot">|</p>
		   			<a href="<?=HOME?>" class="text-nav-foot"> Inicio </a></p> 
		   			<p class="separador-nav-foot">|</p>
		   			<a href="proyectos" class="text-nav-foot">Proyectos</a>
		   			<p class="separador-nav-foot">|</p>
		   			<a class="text-nav-foot">Blog</a>
		   			<p class="separador-nav-foot">|</p>
		   			<a href="about" class="text-nav-foot">About</a>
		   			<p class="separador-nav-foot">|</p>
	   			</ul>
	      	</div>
	    </div>
	    <div class="col-lg-12">
	    	
	    	<div class="row">
	    	<hr>
	    		<div class="col-sm-4 col-lg-4 header-foot-left">
	    			<a class="a-ancaor" href="<?=HOME?>"><h1 class="h1-footer">Ancaor <span style="color:red;">.com </span> </h1></a>
	    		</div>
	    		<div class="col-sm-4 col-lg-4 header-foot-center">
	    			<p> <?php echo COPY ?> </p>
	    			<div class="logo-foot">
						<img class="img-logo-foot" src="<?=DIR_RS?>images/gh-icon.png" alt="gh-icon">
					</div>
	    		</div>
	    		<div class="col-sm-4 col-lg-4 header-foot-right">
	    			<p> Diseñado y Desarrollado por Ancaor </p>
	    			<p> Docs <a target="_blank" class="about-foot" href="https://creativecommons.org/licenses/by/3.0/">CC BY 3.0.</a></p>
	    		</div>
	    	</div>
	    </div>
	    <div class="col-lg-12 powered">
	    	<div class="row">

	    		<div class="col-sm-2 col-lg-1">
	    			<p class="txt3">Powered by:</p>	
	    			<!-- <p><a target="_blank" class="about-foot" href="about">About</a></p> -->

	    		</div>
	    		<div class="col-sm-4 col-lg-4">
	    			<div class="logo-foot">
						<img class="img-logo-foot" src="<?=DIR_RS?>images/php-icon.png" alt="php-icon">
						<img class="img-logo-foot" src="<?=DIR_RS?>images/html5-icon.png" alt="html5-icon">
						<img class="img-logo-foot" src="<?=DIR_RS?>images/css3-icon.png" alt="css3-icon">
						<img class="img-logo-foot" src="<?=DIR_RS?>images/jq-icon.png" alt="jq-icon">
						<img class="img-logo-foot" src="<?=DIR_RS?>images/bs-icon.png" alt="bs-icon">
					</div>

	    		</div>
	    	</div>	    	
	    </div>
	</div>
  </div>
</section>

<!-- jQuery -->
<!-- <script src="<?=DIR_RS?>js/jquery.js"></script> -->
<!-- Bootstrap Core JavaScript -->
<script src="<?=DIR_BS?>js/bootstrap.min.js"></script>	