<!-- Metas -->
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, user-scalable=no">
<base href="<?=BASE;?>" target="_self" />
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="Author" content="<?=AUTHOR;?>" />
<meta property='og:locale' content='es_ES'/>
<meta property='og:type' content='website'/>
<meta property='og:site_name' content='<?= WEBSITE ?>'/>
<meta property='fb:app_id' content='<?= FB_ID ?>'/>
<meta name="robots" content="index,follow">
<meta name="description" content="Portafolio Ancaor, Proyectos Web, Escritorio y Móviles ">
<meta name="keywords" content="ANCAOR,PORTAFOLIO">