<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<!-- Meta, title, CSS, favicons, etc. -->
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<base href="<?=BASE?>" target="_top" />
<meta name="viewport" content="width=device-width, initial-scale=1">
<!-- Bootstrap -->
<link href="<?=DIR_LIBS?>bootstrap/css/bootstrap.min.css" rel="stylesheet">
<!-- Font Awesome -->
<link href="<?=DIR_LIBS?>font-awesome/css/font-awesome.min.css" rel="stylesheet">
<!-- NProgress -->
<link href="<?=DIR_LIBS?>nprogress/nprogress.css" rel="stylesheet">
<!-- iCheck -->
<link href="<?=DIR_LIBS?>iCheck/skins/flat/green.css" rel="stylesheet">
<!-- bootstrap-progressbar -->
<link href="<?=DIR_LIBS?>bootstrap-progressbar/css/bootstrap-progressbar-3.3.4.min.css" rel="stylesheet">
<!-- JQVMap -->
<link href="<?=DIR_LIBS?>jqvmap/dist/jqvmap.min.css" rel="stylesheet"/>
<!-- bootstrap-daterangepicker -->
<link href="<?=DIR_LIBS?>bootstrap-daterangepicker/daterangepicker.css" rel="stylesheet">
<!-- jquery Confirm -->
<link href="<?=DIR_LIBS?>jqueryConfirm/jquery-confirm.min.css" rel="stylesheet">

<!-- Custom Theme Style -->
<link href="<?=DIR_RS?>css/main.css" rel="stylesheet">

<!-- include summernote css/js-->
<link href="http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.2/summernote.css" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="//cdnjs.cloudflare.com/ajax/libs/codemirror/3.20.0/codemirror.css">
<link rel="stylesheet" type="text/css" href="//cdnjs.cloudflare.com/ajax/libs/codemirror/3.20.0/theme/monokai.css">

<!-- Custom Theme Style -->
<link href="<?=DIR_RS?>panel/css/custom.min.css" rel="stylesheet">
<!-- Custom Theme Style -->
<link href="<?=DIR_RS?>css/main.css" rel="stylesheet">
<!-- jQuery 1.11 -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
<!-- /jQuery 1.11 -->
<!-- jquery Confirm -->
<script type="text/javascript" src="<?=DIR_LIBS?>jqueryConfirm/jquery-confirm.min.js"></script>
<!-- jquery Confirm -->
