<section id="redes">
	<div class="container cont-redes">
		<div class="row">
			<div class="col-lg-12 header-redes">
				<h3 class="txt3"> Mis Redes Sociales: </h3>
			</div>
		</div>
		<div class="row row-redes">
			<div class="col-lg-12 body-redes">
				<div class="div-ico-redes">
					<img class="img-ico-redes" src="<?=DIR_RS?>images/fb-icon.png" alt="fb-icon">
				</div>
				<div class="div-ico-redes">
					<img class="img-ico-redes" src="<?=DIR_RS?>images/tw-icon.png" alt="tw-icon">
				</div>
				<div class="div-ico-redes">
					<img class="img-ico-redes" src="<?=DIR_RS?>images/goo-icon.png" alt="goo-icon">
				</div>
			</div>
		</div>
	</div>
</section>