<!DOCTYPE html>
<html lang="es">
<?php include VIEWS.'includes/panel-head.inc'; ?>
<title></title>
</head>
<!-- BODY -->
<body class="nav-md body-panel">
<!-- div container -->
<div class="container body">
  <!-- main_container -->  
  <div class="main_container">
    <?php include VIEWS.'includes/panel-menu.inc'; ?>
    <?php include VIEWS.'includes/panel-top-navigation.inc' ?>
    <!-- page content -->
    <div class="right_col" role="main">
        <!-- Header Pages -->
        <div class="header-pages">   
          <div class="col-md-12 col-sm-12 col-xs-12">
            <div style="width: 90%;height: 430px;margin:30px auto;">
              <iframe style="width: 100%;height: 100%;" src="https://www.youtube.com/embed/-EHkKoGczhk" frameborder="0" allowfullscreen></iframe>
            </div>
          </div>
        </div>
        <!-- /header pages -->
    </div>
    <!-- /page content -->      
  </div>
  <!-- main container -->
</div>
<!-- div container -->
<!-- /main_container -->
<?php include VIEWS.'includes/panel-footer-files.inc' ?>
<?php include VIEWS.'includes/panel-footer.inc' ?>
</body>
<!-- /BODY -->
</html>
