<!DOCTYPE html>
<html lang="es">
<?php include VIEWS.'includes/panel-head.inc'; ?>
<title></title>
</head>
<!-- BODY -->
<body class="nav-md body-panel">
<!-- div container -->
<div class="container body">
  <!-- main_container -->  
  <div class="main_container">
    <?php include VIEWS.'includes/panel-menu.inc'; ?>
    <?php include VIEWS.'includes/panel-top-navigation.inc' ?>
    <!-- page content -->
    <div class="right_col" role="main">
      <!-- Header Pages -->
      <div class="header-pages">   
          <div class="col-md-12 col-sm-12 col-xs-12">
            <!-- x panel -->
            <div class="x_panel">
              <div class=" row x_title">
                <div class="col-md-8 col-xs-11">  
                <h2 class="h2-none" style="width:100%;"><span class="glyphicon glyphicon-user"></span> Perfil de Usuario </h2>
                </div>
                <div class="col-md-4 col-xs-1" style="text-align:right;">             
                  <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                </div> 
                
              </div>
              <!-- x content-->
              <div class="x_content"> 
                <?php include VIEWS.'panel/forms/form-perfil.inc.php' ?>
              </div>
              <!-- x content -->
            </div> 
            <!-- x panel -->
          </div>
      </div>
      <!-- /header pages -->
    </div>
    <!-- /page content -->
  </div>
  <!-- main container -->
</div>
<!-- div container -->
<!-- /main_container -->
<?php include VIEWS.'includes/panel-footer-files.inc' ?>
<?php include VIEWS.'includes/panel-footer.inc' ?>
</body>
<!-- /BODY -->
</html>
