<head>
<base href="<?=BASE?>" target="_top">
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<!-- Meta, title, CSS, favicons, etc. -->
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<!-- Bootstrap -->
<link href="<?=DIR_LIBS?>bootstrap/css/bootstrap.min.css" rel="stylesheet">
<!-- Font Awesome -->
<link href="<?=DIR_LIBS?>font-awesome/css/font-awesome.min.css" rel="stylesheet">
<!-- NProgress -->
<link href="<?=DIR_LIBS?>nprogress/nprogress.css" rel="stylesheet">
<!-- iCheck -->
<link href="<?=DIR_LIBS?>iCheck/skins/flat/green.css" rel="stylesheet">
<!-- bootstrap-progressbar -->
<link href="<?=DIR_LIBS?>bootstrap-progressbar/css/bootstrap-progressbar-3.3.4.min.css" rel="stylesheet">
<!-- Datatables -->
<link href="<?=DIR_LIBS?>datatables.net-bs/css/dataTables.bootstrap.min.css" rel="stylesheet">
<link href="<?=DIR_LIBS?>datatables.net-buttons-bs/css/buttons.bootstrap.min.css" rel="stylesheet">
<link href="<?=DIR_LIBS?>datatables.net-fixedheader-bs/css/fixedHeader.bootstrap.min.css" rel="stylesheet">
<link href="<?=DIR_LIBS?>datatables.net-responsive-bs/css/responsive.bootstrap.min.css" rel="stylesheet">
<link href="<?=DIR_LIBS?>datatables.net-scroller-bs/css/scroller.bootstrap.min.css" rel="stylesheet">
<!-- JQVMap -->
<link href="<?=DIR_LIBS?>jqvmap/dist/jqvmap.min.css" rel="stylesheet"/>
<!-- bootstrap-daterangepicker -->
<link href="<?=DIR_LIBS?>bootstrap-daterangepicker/daterangepicker.css" rel="stylesheet">
<!-- jquery Confirm -->
<link href="<?=DIR_LIBS?>jqueryConfirm/jquery-confirm.min.css" rel="stylesheet">
<!-- Main Theme Style -->
<link href="<?=DIR_RS?>css/main.css" rel="stylesheet">
<!-- LidPanel Theme Style -->
<link href="<?=DIR_RS?>panel/css/custom.min.css" rel="stylesheet">
<!-- Main Theme Style -->
<!-- <link href="<?=DIR_RS?>css/panel/lidpanel.css" rel="stylesheet"> -->
<!-- jQuery 1.11 -->
<script type="text/javascript" src="<?=DIR_LIBS?>jquery/1.11.0/jquery.min.1.11.0.js"></script>
<!-- /jQuery 1.11 -->
<!-- jquery Confirm -->
<script type="text/javascript" src="<?=DIR_LIBS?>jqueryConfirm/jquery-confirm.min.js"></script>
<script type="text/javascript" src="<?=DIR_LIBS?>clipboard/clipboard.min.js"></script>


