<!DOCTYPE html>
<html lang="es">
<head>
<?php include (VIEWS.'modulos/head.phtml') ?>
<title>Pagina Principal</title>
</head>
<body>
<section>
<div class="logo col-md-12">
	<div class="col-md-4">
		<a href="<?=HOME?>"><img class="img-logo" src="<?=IMAGE?>logo.png" alt=""> </a>
	</div>
	<div class="data-logo col-md-8">
		<p class="txt-logo1">info@dominio.org.pe</p>
		<div class="icons">
			<span class="icon icon-fb"><i class="fa fa-facebook" aria-hidden="true"></i></span>
			<span class="icon icon-tw"><i class="fa fa-twitter" aria-hidden="true"></i></span>
		</div>
		<div class="busqueda">
			<form class="navbar-form navbar-right" role="search">
		        <div class="form-group">
		          <input type="text" class="form-control input-busqueda" placeholder="Busca en el Sitio">
		        </div>
		        <button type="submit" class="btn btn-primary btn-busqueda">Buscar</button>
		    </form>	
		</div>
	</div>

</div>
</section>
<?php include (VIEWS.'modulos/navprincipal.phtml') ?>
<!-- 
<div id="slider_wrap">
    <ul style="display: none;">
		<li lcms_img="<?=IMAGE?>qw.jpg">
		<h4 id="txt_heading">Diseño de Páginas Web a Medida</h4>
		<br>

            <a href="" class="boton">Ver Más</a>           
		</li>
		<li lcms_img="<?=IMAGE?>life.jpg">Any content</li>
		<li lcms_img="<?=IMAGE?>gotas.jpg">test 3</li>
	</ul>
</div> -->

<div class="container-image-header">
	<div class="row-image-header">
		<div class="cont-img">
			<!-- <img src="<?=IMAGE?>writecode.png" alt=""> -->
		</div>
	</div>
</div>
<section id="body">
	<div class="body-data">
		<div class="body-post col-md-8">
			<div class="noticias">
				<h3 style="text-align: center;">CONTACTENOS</h3>
			<form action="" id="formdata" method="POST" class="form-horizontal form-label-left" novalidate>
			  <!-- ITEM -->
			  <div class="item form-group">
			    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="name">
			      Asunto: <span class="required">*</span>
			    </label>
			    <div class="col-md-5 col-sm-5 col-xs-12">
			      <input id="user" class="form-control col-md-7 col-xs-12"  value="">
			    </div>
			  </div>
			  <!-- /ITEM -->

			  <!-- ITEM -->
			  <div class="item form-group">
			    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="name">
			      Nombre y Apellido <span class="required">*</span>
			    </label>
			    <div class="col-md-5 col-sm-5 col-xs-12">
			    <input id="nompage" class="form-control col-md-7 col-xs-12" data-validate-length-range="5,20" name="nompage" placeholder="" value="" required="required" type="text">
			    </div>
			  </div>
			  <!-- /ITEM -->
			  <!-- ITEM -->
			  <div class="item form-group">
			    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="name">
			      Ciudad <span class="required">*</span>
			    </label>
			    <div class="col-md-5 col-sm-5 col-xs-12">
			    <input id="nompage" class="form-control col-md-7 col-xs-12" data-validate-length-range="5,20" name="nompage" placeholder="" value="" required="required" type="text">
			    </div>
			  </div>
			  <!-- /ITEM -->
			  <!-- ITEM -->
			  <div class="item form-group">
			    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="name">
			      Pais <span class="required">*</span>
			    </label>
			    <div class="col-md-5 col-sm-5 col-xs-12">
			    <input id="nompage" class="form-control col-md-7 col-xs-12" data-validate-length-range="5,20" name="nompage" placeholder="" value="" required="required" type="text">
			    </div>
			  </div>
			  <!-- /ITEM -->
				<!-- ITEM -->
			  <div class="item form-group">
			    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="name">
			      Institución <span class="required">*</span>
			    </label>
			    <div class="col-md-5 col-sm-5 col-xs-12">
			    <input id="nompage" class="form-control col-md-7 col-xs-12" data-validate-length-range="5,20" name="nompage" placeholder="" value="" required="required" type="text">
			    </div>
			  </div>
			  <!-- /ITEM -->
			  <!-- ITEM -->
			  <div class="item form-group">
			    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="name">
			      Cargo <span class="required">*</span>
			    </label>
			    <div class="col-md-5 col-sm-5 col-xs-12">
			    <input id="nompage" class="form-control col-md-7 col-xs-12" data-validate-length-range="5,20" name="nompage" placeholder="" value="" required="required" type="text">
			    </div>
			  </div>
			  <!-- /ITEM -->
			   <!-- ITEM -->
			  <div class="item form-group">
			    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="name">
			      Teléfono <span class="required">*</span>
			    </label>
			    <div class="col-md-5 col-sm-5 col-xs-12">
			    <input id="nompage" class="form-control col-md-7 col-xs-12" data-validate-length-range="5,20" name="nompage" placeholder="" value="" required="required" type="text">
			    </div>
			  </div>
			  <!-- /ITEM -->
			  			   <!-- ITEM -->
			  <div class="item form-group">
			    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="name">
			      E-mail	<span class="required">*</span>
			    </label>
			    <div class="col-md-5 col-sm-5 col-xs-12">
			    <input id="nompage" class="form-control col-md-7 col-xs-12" data-validate-length-range="5,20" name="nompage" placeholder="" value="" required="required" type="text">
			    </div>
			  </div>
			  <!-- /ITEM -->
			   <div class="ln_solid"></div>
			    <div class="form-group">
			       <div class="col-md-6 col-md-offset-3">
			              <!-- <button type="reset" class="btn btn-primary">Cancel</button> -->
			     	<button id="btnenviar" type="submit" class="btn btn-success"><i class="fa fa-paper-plane"></i> Enviar </button>
			        </div>
			    </div>
			</form>
			</div>
		</div>
		<?php include (VIEWS.'modulos/widget.phtml') ?>
	</div>
	<!-- <div class="clear" style="clear:both;"></div>	 -->
</section>
<?php include (VIEWS.'modulos/semi-footer.phtml') ?>	
<?php include (VIEWS.'modulos/footer.phtml') ?>	
</body>
</html>