<!DOCTYPE html>
<html lang="es">
<head>
<?php include ('public/views/modulos/head.phtml') ?>
<title>Pagina Principal</title>
</head>
<body>

<?php include ('public/views/modulos/navprincipal.phtml') ?>
<div class="container-image-header">
	<div class="row-image-header">
		<div class="cont-img">
			<img src="<?=IMAGE?>writecode.png" alt="">
		</div>
	</div>
</div>
<section id="body">
	<div class="row">
		<div class="col-md-12" style="text-align: center;">
			<h3>Usted no tiene autorización, por favor inicie sesión</h3>
		</div>
	</div>
</section>
<?php include ('public/views/modulos/footer.phtml') ?>	
</body>
</html>