<!DOCTYPE html>
<html lang="es">
<?php include HTML_DIR.'includes/panel-head.inc'; ?>
<title></title>
</head>
<!-- BODY -->
<body class="nav-md">
<!-- div container -->
<div class="container body">
  <!-- main_container -->  
  <div class="main_container">
    <?php include HTML_DIR.'includes/panel-menu.inc'; ?>
    <?php include HTML_DIR.'includes/panel-top-navigation.inc' ?>
    <!-- page content -->
    <div class="right_col" role="main">
      <!-- Header Pages -->
      <div class="header-pages">   
        <div class="col-md-12 col-sm-12 col-xs-12">
          <!-- x panel -->
          <div class="x_panel">
            <div class=" row x_title">
              <div class="col-md-8 col-xs-6">  
              <h2 class="h2-none" style="width:100%;"><span class="glyphicon glyphicon-book"></span> Detalles de las Páginas </h2>
              </div>
              <div class="col-md-4 col-xs-6" style="text-align:right;">
                <a class="well well-sm"> Páginas <span class="badge" style="background-color:rgb(46, 109, 164);color:white;"> <?=count($datos)?> </span></a>
                <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
              </div>        
            </div>
            <!-- x content-->
            <div class="x_content"> 
            <div class="data-page-panel">
              <div class="" role="tabpanel" data-example-id="togglable-tabs">
                <ul id="tabPages" class="nav nav-tabs bar_tabs" role="tablist">
                  <li role="presentation" class="active">
                  	<a class="a-tab" href="#lpages" id="lpages-tab" role="tab" data-toggle="tab" aria-expanded="false">Listado</a>
                  </li>
                </ul>
                <div id="myTabContent" class="tab-content">
                  <div role="tabpanel" class="tab-pane fade active in" id="lpages" aria-labelledby="home-tab">             
                  <div class="row">
                    <div class="col-md-12 table-responsive">
                      <table class="table table-striped table-hover ">
                      <thead>
                        <tr>
                          <th> # (ID) </th>
                          <th> Nombre Dato</th>
                        </tr>
                      </thead>
                      <tbody>
                       <?php 
                       foreach ($datos as $value) { ?>
                        <tr class="success" id="tdata">
                          <td> <?=$value['id_Dato']?> </td>
                          <td> <?=$value['nom_Dato']?>  </td>
                        </tr> 
                       <?php } ?>          
                      </tbody>
                      </table> 
                      <p></p>
                    </div>
                  </div>   
                  </div>             
                </div>
              </div>
            </div> 
            </div>
            <!-- x content -->
          </div> 
          <!-- x panel -->
          </div>
        </div>
      </div>
      <!-- /header pages -->
    </div>
    <!-- /page content -->
  </div>
  <!-- main container -->
</div>
<!-- div container -->
<!-- /main_container -->
<?php include HTML_DIR.'includes/panel-footer-files.inc' ?>
<?php include HTML_DIR.'includes/panel-footer.inc' ?>
</body>
<!-- /BODY -->
</html>
