<!DOCTYPE html>
<html lang="es">
<?php include HTML_DIR.'includes/panel-head.inc'; ?>
<title> Panel de Administración </title>
</head>
<!-- BODY -->
<body class="nav-md">
  <div class="container body">
    <!--  Main-Container -->
    <div class="main_container">
    <?php include HTML_DIR.'includes/panel-menu.inc'; ?>
    <?php include HTML_DIR.'includes/panel-top-navigation.inc' ?>    
      <!-- page content -->
      <div class="right_col" role="main">
        <!-- top tiles -->
        <div class="col-md-4 col-sm-4 col-xs-6 tile_stats_count">
            <span class="count_top"><i class="fa fa-user"></i> Visitas en la Página</span>
            <div class="count">20</div>
            <span class="count_bottom"><i class="green">4% </i> Con respecto a la semana anterior</span>
        </div>
        <!-- /top tiles -->
      </div>
      <!-- /page content -->
    </div>
     <!--  /Main-Container -->
  </div>
<!-- /BODY -->
<?php include HTML_DIR.'includes/panel-footer-files.inc' ?>
<?php include HTML_DIR.'includes/panel-footer.inc' ?>
</body>
</html>
