
                      
                      
                      <div class="col-md-12 col-xs-12 header-body">
<h2 class="title-body">Bienvenido</h2>			  
<h3>Portafolio Ancaor</h3>
	<!-- <img src="resources/images/wolf.png" alt=""> -->
	<!-- <p><a class="btn btn-primary btn-lg btn-ancaor">Mis proyectos</a></p> -->
</div>
<div class="col-lg-12 body-body">
	<div class="row">
		<div class="col-md-8">
		<h3 class="title-p">Sobre Mi:</h3>
		<p>No hay mucho que decir, soy una persona que le gusta aprender nuevas cosas cada día, sobre todo en el ámbito tecnológico de desarrollo de aplicaciones web y escritorio. </p>
		<h4>Mis Conocimientos en lenguajes de Programación:</h4>
			<li>PHP nivel Intermedio (POO, PDO)</li>
			<li>JS nivel Intermedio (DOM, POO)</li>
			<li>SQL nivel básico </li>
			<li>Java nivel básico </li>
			<li>Css3 y html5 - nivel medio (Aclaro, no soy diseñador, solo lo uso para dar un plus)</li>
		<h4>Lenguajes Aprendiendo:</h4>
			<li>Python</li> 
			<li>Lua</li>
			<li>Visual Basic</li>	
		<h3>Sobre la web </h3>
			<p>Es un portafolio con mis proyectos Personales o Externos.Mi meta actual es ser un programador back-end profesional</p>
		<h4>Sobre el Diseño (Front-end)</h4>
			<p>Es un diseño básico realizado en html5, css3 con ayuda del framework bootstrap 3.
				También se está trabajando bajo el ideal de Responsive design</p>
		<h4>Sobre la Programación(Back-end)</h4>	
			<p>Realizado en php, js, ajax, jquery , con una arquitectura MVC para la creación de un CMS para esta misma lo cual la convierte en una web autoadministrable </p>		            
		</div>
		<div class="col-md-4">
			<div style="width:100%;" class="cont-img">
				<img style="width:100%;" src="resources/images/eva.jpg" class="img-thumbnail">
			</div>
			<div style="width:100%;" class="cont-img">
				<img style="width:100%;" src="resources/images/mio.jpg" class="img-thumbnail img-rounded img-circle">
			</div>
		</div>
	</div>
</div>                                                                                                                                                                                                                                       