<!DOCTYPE html>
<html lang="es">
<?php include VIEWS.'includes/panel-head.inc'; ?>
<title></title>
<script>
  $(document).ready(function(){
    var data = $("#val-cant").attr('data');
    $("#c-title").text(data);
  });
</script>
</head>
<!-- BODY -->
<body class="nav-md body-panel">
<!-- Modal -->
<div class="modal" id="modal-fullscreen" tabindex="-1" role="dialog" aria-labelledby="ModalImage">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
<!--       <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel"></h4>
      </div> -->
      <div class="modal-body">
      <div class="col-xs-10 col-xs-push-1">
        <img id="img-full" src="" alt="" style="width: 100%;">
      </div>
      <div class="clearfix"></div>
      <!-- Trigger -->
   <!--    <button class="btn" data-clipboard-action="copy" data-clipboard-target="#enlace-image" data-toggle="tooltip" data-placement="top" title="Copiar al portapapeles">
         <i class="fa fa-files-o" aria-hidden="true" ></i>
      </button>
       <button class="btn"  type="button" class="close" data-dismiss="modal" aria-label="Close">
        <i class="fa fa-times" aria-hidden="true"></i>
       </button> -->
      </div>
     <!--  <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div> -->
    </div>
  </div>
</div>
<!-- / Modal -->
<!-- Modal -->
<div class="modal" id="modal-image" tabindex="-1" role="dialog" aria-labelledby="ModalImage">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <!-- <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel"></h4>
      </div> -->
      <div class="modal-body">
        <div class="col-xs-10">
          <input id="enlace-image" type="text" value="" class="form-control">

        </div>
        <div class="col-xs-2" style="padding-left: 0;padding-right: 0;">
          <!-- Trigger -->
          <button class="btn" id="icon-copy" data-clipboard-action="copy" data-clipboard-target="#enlace-image" data-toggle="tooltip" data-placement="top" title="Copiar al portapapeles">
             <i class="fa fa-files-o" aria-hidden="true" ></i>
          </button>
          <button class="btn"  type="button" class="close" data-dismiss="modal" aria-label="Close" >
            <i class="fa fa-times" aria-hidden="true"></i>
          </button>
          
        </div>
        <div class="clearfix"></div>
      </div>
     <!--  <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div> -->
    </div>
  </div>
</div>
<!-- / Modal -->
<!-- div container -->
<div class="container body">
  <!-- main_container -->  
  <div class="main_container">
    <?php include VIEWS.'includes/panel-menu.inc'; ?>
    <?php include VIEWS.'includes/panel-top-navigation.inc' ?>
        <!-- page content -->
        <div class="right_col" role="main">
          <div class="">
            <div class="page-title">
              <div class="title_left">
                <h3> Galeria de Imagenes <small> </small> </h3>
              </div>
            </div>
            <div class="clearfix"></div>
            <div class="row">
              <div class="col-md-12">
                <div class="x_panel">
                  <div class=" row x_title">
                    <div class="col-md-8 col-xs-6">  
                    <h2 class="h2-none" style="width:100%;"><span class="fa fa-image"></span> Carpeta General </h2>
                    </div>
                    <div class="col-md-4 col-xs-6" style="text-align:right;">
                      <a class="well well-sm"> Imagenes <span id="c-title" class="badge" style="background-color:rgb(46, 109, 164);color:white;"> 
                        0
                      </span>
                      </a>
                      <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                    </div>        
                  </div>
                  <div class="x_content">
                    <div class="row">
                    <?php  
                    $cantidad = 0;
                    $dir = "./public/resources/images";
                    $dirver = is_dir($dir); 
                    if ($dirver){
                      if ($dh = opendir($dir)){   
                         while (($file = readdir($dh)) !== false){
                          $size = filesize($dir.'/'.$file)/1024;
                          $jpg = strpos($file, "jpg");
                          $png = strpos($file, "png");
                          $gif = strpos($file, "gif");
                          if ($jpg !== false || $png !== false || $gif !== false ){
                            $cantidad++;
                    ?>
                    <!-- Imagen -->
                    <div class="col-md-55">
                      <div class="thumbnail">
                        <div class="image view view-first"> 
                          <img class="img-data" style="width: 100%; display: block;" data="<?=HOME.IMAGE.utf8_encode($file)?>" src="<?=IMAGE?><?=utf8_encode($file)?>" alt="image" />
                          <div class="mask no-caption">
                            <!-- <p>Your Text</p> -->
                            <div class="tools tools-bottom">
                                <a class="mostrar-image btn-tools"><i class="fa fa-arrows-alt"></i></a>
                                <a class="enlace-image btn-tools"><i class="fa fa-link"></i></a>
                                <!-- <a class="delete-image btn-tools"><i class="fa fa-times"></i></a> -->
                            </div>
                          </div>
                        </div>
                        <div class="caption">
                        <span><strong><?=utf8_encode($file)?></strong></span>
                        <p><?=round($size,2).' kb'?></p>
                        </div>
                      </div>
                    </div>
                    <!-- / Imagen -->
                    <?php 
                        } 
                      }
                      closedir($dh);
                      } 
                    } 
                     ?>
                    </div>
                     <div> <h4>Total de imagenes encontradas <span id=val-cant data=<?=$cantidad?>><?=$cantidad?></span>  </h4> </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <!-- /page content -->     
  </div>
  <!-- main container -->
</div>
<!-- div container -->
<!-- /main_container -->
<?php include VIEWS.'includes/panel-footer-files.inc' ?>
<?php include VIEWS.'includes/panel-footer.inc' ?>
</body>
<!-- /BODY -->
</html>
