<section id="enlaces">
	<div class="cont-enlaces">
		<div class="col-md-6">
			<span>
				Vigilantes del Agua tiene el objetivo de provomer la cultura del cuidado del Agua
			</span>
		</div>
		<div class="col-md-3">
			<h4>Enlaces de Interes</h4>
			<ul>
				<li><a style="color: rgb(44, 62, 80);" href="nosotros">Quienes Somos</a></li>
			</ul>
		</div>
		<div class="col-md-3">
			<p>
				Nosotros
			</p>
			<p> Perú Jr. Av Lugar Lima - Perú.  <br>
			Tel: (511) 000-0000 </p>
		</div>
	</div>
	<div class="clear" style="clear:both;"></div>
</section>
<section id="footer">
	<div class="cont-footer">	
		<p>Ila Perú 2017  </p>
	</div>
</section>
<!-- Bootstrap -->
<script src="<?=DIR_LIBS?>bootstrap/js/bootstrap.min.js"></script>
<!-- Configuracion del Slider -->
<script language="javascript" src="public/resources/js/confSlider.js"></script>
