<div class="header-nav">
  <div class="cont-nav">
    <div class="menu-responsive">
      <div class="texto-menu">
        <img class="img-logo" src="<?=IMAGE?>logo.png" alt="">
      </div>
      <div class="icono-menu">
        <span><i class="fa fa-bars" aria-hidden="true"></i></span>
      </div>
    </div>
    <nav class="nav-cabecera" id="ncab">
    <ul>
      <li class="none"><a  class="normal" href="<?=HOME?>">Inicio</a></li>
      <li class="none"><a  class="normal" href="nosotros"> Quienes Somos </a></li>
      <li class="none"><a class="normal" href="labor"> Que Hacemos </a>
      </li>
      <li class="none"><a class="normal" href="unete"> Como pertenecer al club </a></li>
       <li class="none"><a class="normal" href="contacto"> Contáctenos </a></li>
    </ul>
  </nav>
  </div> 
</div>