<section id="other">
	<div class="cont-other">
		<div class="other-info col-md-4">
			<div class="cont-image-info">
				<img src="<?=IMAGE?>equipo.png" alt="">
			</div>
		</div>
		<div class="other-info col-md-4">
			<h3>Actividades</h3>
			<ul>
				<li>Exposiciones</li>
				<li>Participación Ciudadana</li>
				<li>Participación Empresarial</li>
			</ul>
		</div>
		<div class="other-info col-md-4">
			<h3>Capacitación</h3>
			<ul>
				<li>Centros educativos</li>
				<li>Instituciones</li>
			</ul>
		</div>
		<div class="clear" style="clear:both;"></div>
	</div>
</section>