		<!-- WIDGET -->
		<div class="col-md-4 body-widget">
			<div class="widget-noticias">		
				<div class="panel panel-info">
					<div class="panel-heading">
					    <h3 class="panel-title">Noticias</h3>
					</div>
					<div class="panel-body">
					   <ul class="list-group">
					   <p class="negrita">| PPK: "No vamos a politizar el agua"</p>
						  El presidente de la República, Pedro Pablo Kuczynski, aseveró que sería gravísimo que, en este momento, se haga demagogia con el acceso a los servicios públicos de agua y saneamiento, e invocó a tomar decisiones responsables sobre la legislación de estos temas.
						</ul>
					</div>
				</div>				
			</div>
		</div>
		<!-- /WIDGET -->
		<div class="col-md-4 body-widget">
			<div class="widget-agua">		
				<div class="panel panel-info">
					<div class="panel-heading">
					    <h3 class="panel-title">El agua</h3>
					</div>
					<div class="panel-body panel-widget">
					   <ul class="list-group">
						  <li class="list-group-item">
						    <i class="fa fa-chevron-right" aria-hidden="true"></i>
						    Ciclo Hidrologico 
						  </li>
						  <li class="list-group-item">
						    <i class="fa fa-chevron-right" aria-hidden="true"></i>
						    Cultura del Agua
						  </li>
						  <li class="list-group-item">
						    <i class="fa fa-chevron-right" aria-hidden="true"></i>
						    Huella hídrica
						  </li>
						</ul>
					</div>
				</div>				
			</div>
		</div>
		<div class="col-md-4 body-widget">
			
			<div class="widget-actualizaciones">
				<div class="widget-agua">		
				<div class="panel panel-info">
					<div class="panel-heading">
					    <h3 class="panel-title">Cuidemos del Agua</h3>
					</div>
					<div class="panel-body">
					   ¿QUÉ SE PUEDE HACER DESDE CASA? <br>
						<ul>
							<li>Cerrar las canillas durante el cepillado de dientes, en lugar de dejar correr el agua.</li>
							<li>No dejar goteando las canillas.</li>
							<li>Usar los baldes para lavar los autos en lugar de la manguera.</li>
							<li>Hacer duchas más cortas.</li>
							<li>Reciclar el agua de la pileta para regar las plantas o baldear la vereda.</li>
							<li>Regar las plantas justo antes del ocaso para evitar que se evapore el agua con el sol.</li>
						</ul>
					</div>
				</div>				
				</div>
			</div>
		</div>
		<div class="clear" style="clear:both;"></div>	