<!DOCTYPE html>
<html lang="es">
<?php include (VIEWS.'modulos/head.phtml') ?>
<head>
<title> Ancaor 2017 </title>
</head>
<body>
<section id="inicio" class="cabecera " >
		<!-- <div class="frase-cabecera">
			<p>Lykrune Web Page</p>
		</div> -->
	<div class="logo-cabecera">
		<h3 id="text-logo" class="text-logo"><img style="width: 20px;" src="<?=DIR_RS?>images/ancaor/Ancaor2017.png" alt="Lykrune Logo"> Ancaor </h3>
		<p id="subtitle-logo" class="subtitle-logo">"Ama lo que haces"</p>
	</div>
	
	<div>
		<nav class="nav-cabecera" id="ncab">
			<ul>
				<li class="none"><a class="normal" href="#inicio">Inicio</a></li>
				<li class="none"><a class="normal" href="#diseno"> Diseños </a></li>
				<li class="none"><a class="normal" href="#about"> About </a></li>
			</ul>
		</nav>
	</div>
	
	<div class="content-cabecera">
		<h3 id="text-logo-body" class="text-logo-body animate-left"><img src="<?=DIR_RS?>images/ancaor/Ancaor2017.png" alt="Ancaor Logo"> Ancaor </h3>
		<div class="separador">
			<hr>
		</div>
		<p id="text-frase" class="text-frase animate-right">Primero debes realizar lo básico, <br>los detalles después.</p>
		<p id="var">  </p>
		<h3 id="none">  </h3>
		<a id="cont-icon" href="#diseno"><i id="icon-down" class="icon-down-open"></i></a>
	</div>
</section>

<section id="diseno"> 
	<h1 id="t-diseno" class="t-diseno">Mis Diseños Web</h1>
	<div class="space">
		<hr>
	</div>
	<div  class="container cont-image">
			<div class="row data-image">
				<div class="col-md-4 col-sm-6 image" >
					<img src="<?=DIR_RS?>images/ancaor.png" alt="">
					<p class="t-data">Ancaor <a target="_blank"  href="http://ancaor.com/">Ver Página</a></p>
				</div>
				<div class="col-md-4 col-sm-6 image">
					<img src="<?=DIR_RS?>images/cdw.png" alt="">
					<p class="t-data">Corp Digital Web <a href="corpdigitalweb">Ver Página</a> </p>
				</div>
				
			</div>
	</div>

</section>

<section id="about">	
	<h1 class="t-diseno">About</h1>
	<div class="space">
		<hr>
	</div>
	<div class="container cont-about">
		<div class="row data-about">
			<div class="col-xs-4 col-md-4 col-sm-4 img-about">
				<img  src="<?=DIR_RS?>images/perfil/perfil.jpg" alt="">
			</div>
			<div class="col-xs-8 col-md-8 col-sm-8 texto-about">
					<p class="frase">Comence a diseñar, con el único fin de crear algo que sea a mi propio gusto. <br>
					En lo personal es algo pesado y a veces llego a frustrame, pero al obtener el resultado deseado te da una gran satisfacción y mas aún cuando puedo decir , YO realice esto :3
					</p>
					<span class="frase-autor"> Anthony (Lykrune) </span>
			</div>
		</div>
	</div>	
</section>

<div class="footer">
		<div class="frase-cabecera">
			<p> <a target="_blank" class="enlace-footer" href="https://www.facebook.com/profile.php?id=100014813495811"><i class="icon-facebook-1"> </i> </a>	<a target="_blank"  class="enlace-footer"  href="https://plus.google.com/u/0/101550641324193523984"><i class="icon-google"> </i></a></p>
			<p> Design by <a class="enlace-footer-ext" href="">
				Lykrune ©
			</a> - Derechos reservados </p>
			<p> Lykrune es parte de <a target="_blank" class="enlace-footer-ext" href="http://ancaor.com">Ancaor</a> </p>
			<!-- <p>  Lykrune Web Page 2017</p> -->
		</div>
</div>
<script src="<?=DIR_LIBS?>jquery/jquery.min-1.4.2.js"
type="text/javascript" charset="utf-8"></script>
<!-- JS -->
<script src="<?=DIR_RS?>js/scroll.js"></script>

</body>
</html>