<?php 
	// print("Index Vista");
	// print_r($dato);
 ?>	
<!DOCTYPE html>
<html lang="es">
<head>
<?php include HTML_DIR.'includes/favicon.inc'; ?>
<?php include HTML_DIR.'includes/metas.inc' ?>
<?php include HTML_DIR.'includes/archivos.inc' ?>
<title>Proyectos</title>
</head>
<body >
<?php include HTML_DIR.'includes/cabecera-top.inc' ?>
<section id="barra-nav">
<div id="cont-nav" class="container">
	<div  class="row div-nav" >
		<nav class="navbar navbar-default navbar-ancaor" data-spy="affix" data-offset-top="190">
		  <div class="nav-cf container-fluid">
		    <div class="navbar-header">
		      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
		        <span class="sr-only"></span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		      </button>
		      <a class="navbar-brand" href="<?=HOME?>">
		         <img style="max-width:40px; margin-top: -10px;" src="<?=DIR_RS?>images/logo.png">
		      </a>
		      <a href="<?=HOME?>" class="navbar-brand">Ancaor</a>
		    </div>
		    <?php include HTML_DIR."includes/nav.inc" ?>
		</div>	
	</div>
</div>	
</section>
<section id="body">
	<div class="container cont-body">
		<div class="row row-body">
			<?php include HTML_DIR.'page/data/data-proyectos.phtml'; ?>
			<div class="col-lg-12 bd-body">
				<div class="project">
		            <h3 class="title-p"><li>Base MVC Project</li></h3>
		            <p class="det-p">
		              <div class="row">
		                <div class="col-md-3 negrita">Tipo:</div>
		                <div class="col-md-9">Programación</div>
		              </div>
		              <div class="row">
		                <div class="col-md-3 negrita">Descripción:</div>
		                <div class="col-md-9">Programación Back-End, Base Para varios proyectos</div>
		              </div>
		              <div class="row">
		                <div class="col-md-3 negrita">Tecnologias Usadas:</div>
		                <div class="col-md-9">PHP,JS(AJAX,JQUERY),SQL</div>
		              </div>
		              <div class="row">
		                <div class="col-md-3 negrita">Estado:</div>
		                <div class="col-md-9">Terminado</div>
		              </div>
		            </p>  
          		</div>

          		<div class="project">
		            <h3 class="title-p"><li>Jinesis 6.0</li></h3>
		            <p class="det-p">
		              <div class="row">
		                <div class="col-md-3 negrita">Tipo:</div>
		                <div class="col-md-9">Pagina Web</div>
		              </div>
		              <div class="row">
		                <div class="col-md-3 negrita">Descripción:</div>
		                <div class="col-md-9">Pagina Web</div>
		              </div>
		              <div class="row">
		                <div class="col-md-3 negrita">Tecnologias Usadas:</div>
		                <div class="col-md-9"><i class="fa fa-html5"></i>  HTML5 + <i class="fa fa-css3"> </i>  CSS3</div>
		              </div>
		              <div class="row">
		                <div class="col-md-3 negrita">Estado:</div>
		                <div class="col-md-9">Terminado</div>
		              </div>
		              <div class="row">
		                <div class="col-md-3 negrita">Pagina Web:</div>
		                <div class="col-md-9"><a target="_blank" href="http://www.jinesistelesup.tk">Jinesis 6.0</a></div>
		              </div>
		            </p>
		        </div>

          		<div class="project">
		            <h3 class="title-p"><li>Sistemas Inmobiliarios</li></h3>
		            <p class="det-p">
		              <div class="row">
		                <div class="col-md-3 negrita">Tipo:</div>
		                <div class="col-md-9">Pagina Web</div>
		              </div>
		              <div class="row">
		                <div class="col-md-3 negrita">Descripción:</div>
		                <div class="col-md-9">Pagina Web</div>
		              </div>
		              <div class="row">
		                <div class="col-md-3 negrita">Tecnologias Usadas:</div>
		                <div class="col-md-9"><i class="fa fa-html5"></i>  HTML5 + <i class="fa fa-css3"> </i>  CSS3</div>
		              </div>
		              <div class="row">
		                <div class="col-md-3 negrita">Estado:</div>
		                <div class="col-md-9">Terminado</div>
		              </div>
		              <div class="row">
		                <div class="col-md-3 negrita">Pagina Web:</div>
		                <div class="col-md-9"><a target="_blank" href="http://sistemasinmobiliarios.pe">Sistemas Inmobiliarios</a></div>
		              </div>
		            </p>
		        </div>
				
				<div class="project">
		            <h3 class="title-p"><li>Apelima Virtual</li></h3>
		            <p class="det-p">
		              <div class="row">
		                <div class="col-md-3 negrita">Tipo:</div>
		                <div class="col-md-9">Front End + Back End</div>
		              </div>
		              <div class="row">
		                <div class="col-md-3 negrita">Descripción:</div>
		                <div class="col-md-9">Pagina web de cursos virtuales</div>
		              </div>
		              <div class="row">
		                <div class="col-md-3 negrita">Tecnologias Usadas:</div>
		                <div class="col-md-9"><i class="fa fa-html5"></i>  HTML5 + <i class="fa fa-css3"> </i>  CSS3</div>
		              </div>
		              <div class="row">
		                <div class="col-md-3 negrita">Estado:</div>
		                <div class="col-md-9">En proceso</div>
		              </div>
		              <div class="row">
		                <div class="col-md-3 negrita">Pagina Web:</div>
		                <div class="col-md-9"><a target="_blank" href="http://www.apelimaperu.com/virtual">Apelima Peru Virtual</a></div>
		              </div>
		            </p>
		        </div>

				<div class="project">
		            <h3 class="title-p"><li>Aniworld</li></h3>
		            <p class="det-p">
		              <div class="row">
		                <div class="col-md-3 negrita">Tipo:</div>
		                <div class="col-md-9">Front End + Back End</div>
		              </div>
		              <div class="row">
		                <div class="col-md-3 negrita">Descripción:</div>
		                <div class="col-md-9">Pagina Web de animes autoadministrable</div>
		              </div>
		              <div class="row">
		                <div class="col-md-3 negrita">Tecnologias Usadas:</div>
		                <div class="col-md-9"><i class="fa fa-html5"></i>  HTML5 + <i class="fa fa-css3"> </i>  CSS3 + PHP + AJAX + JS </div>
		              </div>
		              <div class="row">
		                <div class="col-md-3 negrita">Estado:</div>
		                <div class="col-md-9">Abandonado</div>
		              </div>
		              <div class="row">
		                <div class="col-md-3 negrita">Pagina Web:</div>
		                <div class="col-md-9"><a target="_blank" href="http://www.ancaor.com/aniworld">Aniworld</a></div>
		              </div>
		            </p>
		        </div>

				<div class="project">
		            <h3 class="title-p"><li>Wolf Dark</li></h3>
		            <p class="det-p">
		              <div class="row">
		                <div class="col-md-3 negrita">Tipo:</div>
		                <div class="col-md-9">Pagina Web</div>
		              </div>
		              <div class="row">
		                <div class="col-md-3 negrita">Descripción:</div>
		                <div class="col-md-9">Pagina Web</div>
		              </div>
		              <div class="row">
		                <div class="col-md-3 negrita">Tecnologias Usadas:</div>
		                <div class="col-md-9"><i class="fa fa-html5"></i>  HTML5 + <i class="fa fa-css3"> </i>  CSS3</div>
		              </div>
		              <div class="row">
		                <div class="col-md-3 negrita">Estado:</div>
		                <div class="col-md-9">Abandonado</div>
		              </div>
		              <div class="row">
		                <div class="col-md-3 negrita">Pagina Web:</div>
		                <div class="col-md-9"><a target="_blank" href="http://www.wolfdark.pe.hu">Wolf Dark</a></div>
		              </div>
		            </p>
		        </div>
		

			</div> 
		</div>
	</div>
</section>
<?php include HTML_DIR.'includes/redes.inc' ?>
<?php include HTML_DIR.'includes/footer.inc' ?>
</body>
</html>
